sudo: required

language: node_js
node_js:
  - "6"

install:
  - npm install -g eslint@3.19.0

services:
  - docker

after_success:
  - docker ps -a
  - docker images -a

env:
  matrix:
    - TEST_IMG=node
    - TEST_IMG=dotnet
    - TEST_IMG=jvm
    - TEST_IMG=python
    - TEST_IMG=ruby
    - TEST_IMG=alt
    - TEST_IMG=rust
    - TEST_IMG=julia
    - TEST_IMG=systems
    - TEST_IMG=dart
    - TEST_IMG=crystal
    - TEST_IMG=ocaml
    - TEST_IMG=swift
    - TEST_IMG=haskell
    - TEST_IMG=objc
    - TEST_IMG=go
    - TEST_IMG=lua
    - TEST_IMG=java
    - TEST_IMG=esolangs
    - TEST_IMG=chapel

script:
  - eslint '**/*.js'
  - make $TEST_IMG
